apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: zkp-integ

---

apiVersion: v1
kind: Pod
metadata:
  name: pulsar-kafka-zookeeper
  labels:
    app: zookeeper
  namespace: zkp-integ
spec:
  containers:
    - name: zookeeper
      image: quay.io/rralhan/zookeeper:latest
      ports:
        - containerPort: 2181


---

apiVersion: v1
kind: Service
metadata:
  name: pulsar-kafka-zookeeper
  namespace: zkp-integ
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

---

apiVersion: v1
kind: Pod
metadata:
  name: pulsar-kafka
  labels:
    app: kafka
  namespace: zkp-integ
spec:
  containers:
    - name: kafka
      image: quay.io/rralhan/kafka:latest
      env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "pulsar-kafka.zkp-integ.svc.cluster.local"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "pulsar-kafka-zookeeper.zkp-integ.svc.cluster.local:2181"
      ports:
        - containerPort: 6667
        - containerPort: 9092

---

apiVersion: v1
kind: Service
metadata:
  name: pulsar-kafka
  namespace: zkp-integ
spec:
  selector:
    app: kafka
  ports:
    - name: "tcp6667"
      protocol: TCP
      port: 6667
      targetPort: 6667
    - name: "tcp9092"
      protocol: TCP
      port: 9092
      targetPort: 9092

---

apiVersion: v1
kind: Pod
metadata:
  name: pulsar-kafka-standalone
  labels:
    app: pulsar
  namespace: zkp-integ
spec:
  containers:
    - name: pulsar
      image: quay.io/rralhan/pulsar:latest
      ports:
        - containerPort: 6650
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pulsar-kafka-pulsar
  namespace: zkp-integ
spec:
  selector:
    app: pulsar
  ports:
    - name: "tcp6650"
      protocol: TCP
      port: 6650
      targetPort: 6650
    - name: "tcp8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
